import type { MediaItem } from './types'

export interface PublicTemplateDef {
  id: string
  name: string
  description: string
  coverUrl: string
  items: MediaItem[]
}

// All covers live in /public/covers/*. Posteres are auto-resolved from folders:
// posters, posters-actors, posters-basketball, posters-basketball-teams,
// posters-movies, posters-football, posters-football-players

export const publicTemplates: PublicTemplateDef[] = [
  {
    id: 'tv-2000-2025',
    name: 'Сериалы 2000–2025',
    description: 'Популярные сериалы с 2000 по 2025 годы',
    coverUrl: '/public/covers/series.png',
    items: [
      { id: 'breaking-bad', title: 'Во все тяжкие', imageUrl: '' },
      { id: 'game-of-thrones', title: 'Игра престолов', imageUrl: '' },
      { id: 'stranger-things', title: 'Очень странные дела', imageUrl: '' },
      { id: 'the-crown', title: 'Корона', imageUrl: '' },
      { id: 'chernobyl', title: 'Чернобыль', imageUrl: '' },
      { id: 'better-call-saul', title: 'Лучше звоните Солу', imageUrl: '' },
      { id: 'true-detective', title: 'Настоящий детектив', imageUrl: '' },
      { id: 'sherlock', title: 'Шерлок', imageUrl: '' },
      { id: 'house-md', title: 'Доктор Хаус', imageUrl: '' },
      { id: 'lost', title: 'Остаться в живых', imageUrl: '' },
      { id: 'dark', title: 'Тьма', imageUrl: '' },
      { id: 'black-mirror', title: 'Чёрное зеркало', imageUrl: '' },
      { id: 'the-boys', title: 'Пацаны', imageUrl: '' },
      { id: 'the-mandalorian', title: 'Мандалорец', imageUrl: '' },
      { id: 'the-last-of-us', title: 'Одни из нас', imageUrl: '' },
      { id: 'mr-robot', title: 'Мистер Робот', imageUrl: '' },
      { id: 'fargo', title: 'Фарго', imageUrl: '' },
      { id: 'westworld', title: 'Мир Дикого Запада', imageUrl: '' },
      { id: 'peaky-blinders', title: 'Острые козырьки', imageUrl: '' },
      { id: 'the-witcher', title: 'Ведьмак', imageUrl: '' },
      { id: 'the-office-us', title: 'Офис (США)', imageUrl: '' },
      { id: 'the-wire', title: 'Прослушка', imageUrl: '' },
      { id: 'band-of-brothers', title: 'Братья по оружию', imageUrl: '' },
      { id: 'the-pacific', title: 'Тихий океан', imageUrl: '' },
      { id: 'dexter', title: 'Декстер', imageUrl: '' },
      { id: 'homeland', title: 'Родина', imageUrl: '' },
      { id: 'narcos', title: 'Нарко', imageUrl: '' },
      { id: 'mindhunter', title: 'Охотник за разумом', imageUrl: '' },
      { id: 'succession', title: 'Наследники', imageUrl: '' },
      { id: 'ted-lasso', title: 'Тед Лассо', imageUrl: '' },
      { id: 'the-handmaids-tale', title: 'Рассказ служанки', imageUrl: '' },
      { id: 'the-queen-gambit', title: 'Ход королевы', imageUrl: '' },
      { id: 'shameless-us', title: 'Бесстыдники (США)', imageUrl: '' },
      { id: 'vikings', title: 'Викинги', imageUrl: '' },
      { id: 'the-expanse', title: 'Пространство', imageUrl: '' },
      { id: 'the-umbrella-academy', title: 'Академия «Амбрелла»', imageUrl: '' },
      { id: 'the-haunting-of-hill-house', title: 'Призраки дома на холме', imageUrl: '' },
      { id: 'severance', title: 'Разделение', imageUrl: '' },
      { id: 'the-bear', title: 'Медведь', imageUrl: '' },
      { id: 'the-white-lotus', title: 'Белый лотос', imageUrl: '' },
      { id: 'the-morning-show', title: 'Утреннее шоу', imageUrl: '' },
      { id: 'silo', title: 'Сило', imageUrl: '' },
      { id: 'andor', title: 'Андор', imageUrl: '' },
      { id: 'the-night-manager', title: 'Ночной администратор', imageUrl: '' },
      { id: 'the-leftovers', title: 'Оставленные', imageUrl: '' },
    ],
  },

  {
    id: 'basketball-players',
    name: 'Баскетбольные игроки',
    description: 'Легенды и звёзды NBA, включая актуальных игроков 2025',
    coverUrl: '/public/covers/basketball-players.jpg',
    items: [
      { id: 'michael-jordan', title: 'Michael Jordan', imageUrl: '' },
      { id: 'lebron-james', title: 'LeBron James', imageUrl: '' },
      { id: 'kobe-bryant', title: 'Kobe Bryant', imageUrl: '' },
      { id: 'kareem-abdul-jabbar', title: 'Kareem Abdul-Jabbar', imageUrl: '' },
      { id: 'magic-johnson', title: 'Magic Johnson', imageUrl: '' },
      { id: 'larry-bird', title: 'Larry Bird', imageUrl: '' },
      { id: 'shaquille-oneal', title: 'Shaquille O\'Neal', imageUrl: '' },
      { id: 'tim-duncan', title: 'Tim Duncan', imageUrl: '' },
      { id: 'hakeem-olajuwon', title: 'Hakeem Olajuwon', imageUrl: '' },
      { id: 'kevin-durant', title: 'Kevin Durant', imageUrl: '' },
      { id: 'stephen-curry', title: 'Stephen Curry', imageUrl: '' },
      { id: 'dirk-nowitzki', title: 'Dirk Nowitzki', imageUrl: '' },
      { id: 'charles-barkley', title: 'Charles Barkley', imageUrl: '' },
      { id: 'david-robinson', title: 'David Robinson', imageUrl: '' },
      { id: 'moses-malone', title: 'Moses Malone', imageUrl: '' },
      { id: 'isiah-thomas', title: 'Isiah Thomas', imageUrl: '' },
      { id: 'scottie-pippen', title: 'Scottie Pippen', imageUrl: '' },
      { id: 'allen-iverson', title: 'Allen Iverson', imageUrl: '' },
      { id: 'dwyane-wade', title: 'Dwyane Wade', imageUrl: '' },
      { id: 'chris-paul', title: 'Chris Paul', imageUrl: '' },
      { id: 'james-harden', title: 'James Harden', imageUrl: '' },
      { id: 'giannis-antetokounmpo', title: 'Giannis Antetokounmpo', imageUrl: '' },
      { id: 'nikola-jokic', title: 'Nikola Jokić', imageUrl: '' },
      { id: 'luka-doncic', title: 'Luka Dončić', imageUrl: '' },
      { id: 'joel-embiid', title: 'Joel Embiid', imageUrl: '' },
      { id: 'kawhi-leonard', title: 'Kawhi Leonard', imageUrl: '' },
      { id: 'damian-lillard', title: 'Damian Lillard', imageUrl: '' },
      { id: 'anthony-davis', title: 'Anthony Davis', imageUrl: '' },
      { id: 'jayson-tatum', title: 'Jayson Tatum', imageUrl: '' },
      { id: 'vince-carter', title: 'Vince Carter', imageUrl: '' },
      { id: 'tracy-mcgrady', title: 'Tracy McGrady', imageUrl: '' },
      { id: 'paul-pierce', title: 'Paul Pierce', imageUrl: '' },
      { id: 'ray-allen', title: 'Ray Allen', imageUrl: '' },
      { id: 'reggie-miller', title: 'Reggie Miller', imageUrl: '' },
      { id: 'patrick-ewing', title: 'Patrick Ewing', imageUrl: '' },
      { id: 'karl-malone', title: 'Karl Malone', imageUrl: '' },
      { id: 'john-stockton', title: 'John Stockton', imageUrl: '' },
      { id: 'steve-nash', title: 'Steve Nash', imageUrl: '' },
      { id: 'gary-payton', title: 'Gary Payton', imageUrl: '' },
      { id: 'dennis-rodman', title: 'Dennis Rodman', imageUrl: '' },
      { id: 'yao-ming', title: 'Yao Ming', imageUrl: '' },
      { id: 'manu-ginobili', title: 'Manu Ginóbili', imageUrl: '' },
      { id: 'tony-parker', title: 'Tony Parker', imageUrl: '' },
      { id: 'carmelo-anthony', title: 'Carmelo Anthony', imageUrl: '' },
      { id: 'dwight-howard', title: 'Dwight Howard', imageUrl: '' },
      { id: 'kevin-garnett', title: 'Kevin Garnett', imageUrl: '' },
      { id: 'dominique-wilkins', title: 'Dominique Wilkins', imageUrl: '' },
      { id: 'alonzo-mourning', title: 'Alonzo Mourning', imageUrl: '' },
      { id: 'james-worthy', title: 'James Worthy', imageUrl: '' },
      { id: 'bill-russell', title: 'Bill Russell', imageUrl: '' },
      { id: 'wilt-chamberlain', title: 'Wilt Chamberlain', imageUrl: '' },
      { id: 'ja-morant', title: 'Ja Morant', imageUrl: '' },
      { id: 'zion-williamson', title: 'Zion Williamson', imageUrl: '' },
      { id: 'shai-gilgeous-alexander', title: 'Shai Gilgeous-Alexander', imageUrl: '' },
      { id: 'tyrese-haliburton', title: 'Tyrese Haliburton', imageUrl: '' },
      { id: 'anthony-edwards', title: 'Anthony Edwards', imageUrl: '' },
      { id: 'devin-booker', title: 'Devin Booker', imageUrl: '' },
      { id: 'donovan-mitchell', title: 'Donovan Mitchell', imageUrl: '' },
      { id: 'jimmy-butler', title: 'Jimmy Butler', imageUrl: '' },
      { id: 'kyrie-irving', title: 'Kyrie Irving', imageUrl: '' },
      { id: 'jaylen-brown', title: 'Jaylen Brown', imageUrl: '' },
      { id: 'bam-adebayo', title: 'Bam Adebayo', imageUrl: '' },
      { id: 'jalen-brunson', title: 'Jalen Brunson', imageUrl: '' },
      { id: 'deaaron-fox', title: "De'Aaron Fox", imageUrl: '' },
      { id: 'jamal-murray', title: 'Jamal Murray', imageUrl: '' },
      { id: 'victor-wembanyama', title: 'Victor Wembanyama', imageUrl: '' },
    ],
  },

  {
    id: 'football-players',
    name: 'Футбольные игроки',
    description: 'Легенды и популярные игроки сейчас',
    coverUrl: '/public/covers/football-players.jpg',
    items: [
      { id: 'lionel-messi', title: 'Lionel Messi', imageUrl: '' },
      { id: 'cristiano-ronaldo', title: 'Cristiano Ronaldo', imageUrl: '' },
      { id: 'neymar', title: 'Neymar', imageUrl: '' },
      { id: 'kylian-mbappe', title: 'Kylian Mbappé', imageUrl: '' },
      { id: 'robert-lewandowski', title: 'Robert Lewandowski', imageUrl: '' },
      { id: 'luka-modric', title: 'Luka Modrić', imageUrl: '' },
      { id: 'kevin-de-bruyne', title: 'Kevin De Bruyne', imageUrl: '' },
      { id: 'mohamed-salah', title: 'Mohamed Salah', imageUrl: '' },
      { id: 'harry-kane', title: 'Harry Kane', imageUrl: '' },
      { id: 'erling-haaland', title: 'Erling Haaland', imageUrl: '' },
      { id: 'karim-benzema', title: 'Karim Benzema', imageUrl: '' },
      { id: 'sergio-ramos', title: 'Sergio Ramos', imageUrl: '' },
      { id: 'xavi', title: 'Xavi', imageUrl: '' },
      { id: 'andres-iniesta', title: 'Andrés Iniesta', imageUrl: '' },
      { id: 'zinedine-zidane', title: 'Zinédine Zidane', imageUrl: '' },
      { id: 'ronaldinho', title: 'Ronaldinho', imageUrl: '' },
      { id: 'ronaldo-nazario', title: 'Ronaldo Nazário', imageUrl: '' },
      { id: 'pele', title: 'Pelé', imageUrl: '' },
      { id: 'diego-maradona', title: 'Diego Maradona', imageUrl: '' },
      { id: 'thierry-henry', title: 'Thierry Henry', imageUrl: '' },
      { id: 'wayne-rooney', title: 'Wayne Rooney', imageUrl: '' },
      { id: 'frank-lampard', title: 'Frank Lampard', imageUrl: '' },
      { id: 'steven-gerrard', title: 'Steven Gerrard', imageUrl: '' },
      { id: 'andrea-pirlo', title: 'Andrea Pirlo', imageUrl: '' },
      { id: 'paolo-maldini', title: 'Paolo Maldini', imageUrl: '' },
      { id: 'gianluigi-buffon', title: 'Gianluigi Buffon', imageUrl: '' },
      { id: 'iker-casillas', title: 'Iker Casillas', imageUrl: '' },
      { id: 'didier-drogba', title: 'Didier Drogba', imageUrl: '' },
      { id: 'samuel-etoo', title: 'Samuel Eto\'o', imageUrl: '' },
      { id: 'luis-suarez', title: 'Luis Suárez', imageUrl: '' },
      { id: 'gareth-bale', title: 'Gareth Bale', imageUrl: '' },
      { id: 'zlatan-ibrahimovic', title: 'Zlatan Ibrahimović', imageUrl: '' },
      { id: 'antoine-griezmann', title: 'Antoine Griezmann', imageUrl: '' },
      { id: 'ngolo-kante', title: 'N\'Golo Kanté', imageUrl: '' },
      { id: 'toni-kroos', title: 'Toni Kroos', imageUrl: '' },
      { id: 'thomas-muller', title: 'Thomas Müller', imageUrl: '' },
      { id: 'marcelo', title: 'Marcelo', imageUrl: '' },
      { id: 'dani-alves', title: 'Dani Alves', imageUrl: '' },
      { id: 'virgil-van-dijk', title: 'Virgil van Dijk', imageUrl: '' },
      { id: 'manuel-neuer', title: 'Manuel Neuer', imageUrl: '' },
      { id: 'jan-oblak', title: 'Jan Oblak', imageUrl: '' },
      { id: 'alisson-becker', title: 'Alisson Becker', imageUrl: '' },
      { id: 'ederson', title: 'Ederson', imageUrl: '' },
      { id: 'sergio-aguero', title: 'Sergio Agüero', imageUrl: '' },
      { id: 'angel-di-maria', title: 'Ángel Di María', imageUrl: '' },
      { id: 'bruno-fernandes', title: 'Bruno Fernandes', imageUrl: '' },
      { id: 'bernardo-silva', title: 'Bernardo Silva', imageUrl: '' },
      { id: 'vinicius-junior', title: 'Vinícius Júnior', imageUrl: '' },
      { id: 'jude-bellingham', title: 'Jude Bellingham', imageUrl: '' },
      { id: 'phil-foden', title: 'Phil Foden', imageUrl: '' },
      { id: 'jamal-musiala', title: 'Jamal Musiala', imageUrl: '' },
      { id: 'bukayo-saka', title: 'Bukayo Saka', imageUrl: '' },
      { id: 'pedri', title: 'Pedri', imageUrl: '' },
      { id: 'gavi', title: 'Gavi', imageUrl: '' },
      { id: 'rodrygo', title: 'Rodrygo', imageUrl: '' },
      { id: 'federico-valverde', title: 'Federico Valverde', imageUrl: '' },
      { id: 'lautaro-martinez', title: 'Lautaro Martínez', imageUrl: '' },
      { id: 'khvicha-kvaratskhelia', title: 'Khvicha Kvaratskhelia', imageUrl: '' },
      { id: 'declan-rice', title: 'Declan Rice', imageUrl: '' },
      { id: 'martin-odegaard', title: 'Martin Ødegaard', imageUrl: '' },
    ],
  },

  {
    id: 'football-teams',
    name: 'Футбольные команды',
    description: 'Популярные клубы',
    coverUrl: '/public/covers/footbal.jpg',
    items: [
      { id: 'real-madrid', title: 'Real Madrid', imageUrl: '' },
      { id: 'barcelona', title: 'Barcelona', imageUrl: '' },
      { id: 'manchester-united', title: 'Manchester United', imageUrl: '' },
      { id: 'manchester-city', title: 'Manchester City', imageUrl: '' },
      { id: 'bayern-munich', title: 'Bayern Munich', imageUrl: '' },
      { id: 'psg', title: 'PSG', imageUrl: '' },
      { id: 'liverpool', title: 'Liverpool', imageUrl: '' },
      { id: 'chelsea', title: 'Chelsea', imageUrl: '' },
      { id: 'arsenal', title: 'Arsenal', imageUrl: '' },
      { id: 'tottenham-hotspur', title: 'Tottenham Hotspur', imageUrl: '' },
      { id: 'atletico-madrid', title: 'Atletico Madrid', imageUrl: '' },
      { id: 'juventus', title: 'Juventus', imageUrl: '' },
      { id: 'ac-milan', title: 'AC Milan', imageUrl: '' },
      { id: 'inter-milan', title: 'Inter Milan', imageUrl: '' },
      { id: 'borussia-dortmund', title: 'Borussia Dortmund', imageUrl: '' },
      { id: 'rb-leipzig', title: 'RB Leipzig', imageUrl: '' },
      { id: 'bayer-leverkusen', title: 'Bayer Leverkusen', imageUrl: '' },
      { id: 'sevilla', title: 'Sevilla', imageUrl: '' },
      { id: 'valencia', title: 'Valencia', imageUrl: '' },
      { id: 'napoli', title: 'Napoli', imageUrl: '' },
      { id: 'roma', title: 'AS Roma', imageUrl: '' },
      { id: 'lazio', title: 'Lazio', imageUrl: '' },
      { id: 'ajax', title: 'Ajax', imageUrl: '' },
      { id: 'benfica', title: 'Benfica', imageUrl: '' },
      { id: 'porto', title: 'Porto', imageUrl: '' },
    ],
  },

  {
    id: 'hollywood-actors',
    name: 'Голливудские актёры',
    description: 'Классические и современные звёзды',
    coverUrl: '/public/covers/film-stars.png',
    items: [
      { id: 'leonardo-dicaprio', title: 'Leonardo DiCaprio', imageUrl: '' },
      { id: 'brad-pitt', title: 'Brad Pitt', imageUrl: '' },
      { id: 'meryl-streep', title: 'Meryl Streep', imageUrl: '' },
      { id: 'denzel-washington', title: 'Denzel Washington', imageUrl: '' },
      { id: 'emma-stone', title: 'Emma Stone', imageUrl: '' },
      { id: 'ryan-gosling', title: 'Ryan Gosling', imageUrl: '' },
      { id: 'tom-cruise', title: 'Tom Cruise', imageUrl: '' },
      { id: 'robert-downey-jr', title: 'Robert Downey Jr.', imageUrl: '' },
      { id: 'scarlett-johansson', title: 'Scarlett Johansson', imageUrl: '' },
      { id: 'chris-evans', title: 'Chris Evans', imageUrl: '' },
      { id: 'natalie-portman', title: 'Natalie Portman', imageUrl: '' },
      { id: 'anne-hathaway', title: 'Anne Hathaway', imageUrl: '' },
      { id: 'matt-damon', title: 'Matt Damon', imageUrl: '' },
      { id: 'ben-affleck', title: 'Ben Affleck', imageUrl: '' },
      { id: 'christian-bale', title: 'Christian Bale', imageUrl: '' },
      { id: 'joaquin-phoenix', title: 'Joaquin Phoenix', imageUrl: '' },
      { id: 'ryan-reynolds', title: 'Ryan Reynolds', imageUrl: '' },
      { id: 'jennifer-lawrence', title: 'Jennifer Lawrence', imageUrl: '' },
      { id: 'margot-robbie', title: 'Margot Robbie', imageUrl: '' },
      { id: 'zendaya', title: 'Zendaya', imageUrl: '' },
      { id: 'robert-de-niro', title: 'Robert De Niro', imageUrl: '' },
      { id: 'al-pacino', title: 'Al Pacino', imageUrl: '' },
      { id: 'tom-hanks', title: 'Tom Hanks', imageUrl: '' },
      { id: 'morgan-freeman', title: 'Morgan Freeman', imageUrl: '' },
      { id: 'samuel-l-jackson', title: 'Samuel L. Jackson', imageUrl: '' },
      { id: 'keanu-reeves', title: 'Keanu Reeves', imageUrl: '' },
      { id: 'hugh-jackman', title: 'Hugh Jackman', imageUrl: '' },
      { id: 'will-smith', title: 'Will Smith', imageUrl: '' },
      { id: 'johnny-depp', title: 'Johnny Depp', imageUrl: '' },
      { id: 'cate-blanchett', title: 'Cate Blanchett', imageUrl: '' },
      { id: 'keira-knightley', title: 'Keira Knightley', imageUrl: '' },
      { id: 'charlize-theron', title: 'Charlize Theron', imageUrl: '' },
      { id: 'emily-blunt', title: 'Emily Blunt', imageUrl: '' },
      { id: 'florence-pugh', title: 'Florence Pugh', imageUrl: '' },
      { id: 'tom-hardy', title: 'Tom Hardy', imageUrl: '' },
      { id: 'benedict-cumberbatch', title: 'Benedict Cumberbatch', imageUrl: '' },
      { id: 'matthew-mcconaughey', title: 'Matthew McConaughey', imageUrl: '' },
      { id: 'daniel-craig', title: 'Daniel Craig', imageUrl: '' },
      { id: 'idris-elba', title: 'Idris Elba', imageUrl: '' },
      { id: 'henry-cavill', title: 'Henry Cavill', imageUrl: '' },
      { id: 'zendaya', title: 'Zendaya', imageUrl: '' },
      { id: 'jake-gyllenhaal', title: 'Jake Gyllenhaal', imageUrl: '' },
      { id: 'andrew-garfield', title: 'Andrew Garfield', imageUrl: '' },
      { id: 'adam-driver', title: 'Adam Driver', imageUrl: '' },
      { id: 'oscar-isaac', title: 'Oscar Isaac', imageUrl: '' },
      { id: 'pedro-pascal', title: 'Pedro Pascal', imageUrl: '' },
      { id: 'tom-holland', title: 'Tom Holland', imageUrl: '' },
      { id: 'woody-harrelson', title: 'Woody Harrelson', imageUrl: '' },
      { id: 'colin-farrell', title: 'Colin Farrell', imageUrl: '' },
      { id: 'jesse-eisenberg', title: 'Jesse Eisenberg', imageUrl: '' },
      { id: 'aaron-paul', title: 'Aaron Paul', imageUrl: '' },
      { id: 'tobey-maguire', title: 'Tobey Maguire', imageUrl: '' },
      { id: 'tom-hiddleston', title: 'Tom Hiddleston', imageUrl: '' },
      { id: 'harrison-ford', title: 'Harrison Ford', imageUrl: '' },
      { id: 'rami-malek', title: 'Rami Malek', imageUrl: '' },
      { id: 'mahershala-ali', title: 'Mahershala Ali', imageUrl: '' },
      { id: 'bryan-cranston', title: 'Bryan Cranston', imageUrl: '' },
      { id: 'bob-odenkirk', title: 'Bob Odenkirk', imageUrl: '' },
    ],
  },

  {
    id: 'basketball-teams',
    name: 'Баскетбольные команды',
    description: 'Популярные клубы NBA',
    coverUrl: '/public/covers/basketball-teams.jpg',
    items: [
      { id: 'los-angeles-lakers', title: 'Los Angeles Lakers', imageUrl: '' },
      { id: 'boston-celtics', title: 'Boston Celtics', imageUrl: '' },
      { id: 'chicago-bulls', title: 'Chicago Bulls', imageUrl: '' },
      { id: 'golden-state-warriors', title: 'Golden State Warriors', imageUrl: '' },
      { id: 'miami-heat', title: 'Miami Heat', imageUrl: '' },
      { id: 'san-antonio-spurs', title: 'San Antonio Spurs', imageUrl: '' },
      { id: 'dallas-mavericks', title: 'Dallas Mavericks', imageUrl: '' },
      { id: 'phoenix-suns', title: 'Phoenix Suns', imageUrl: '' },
      { id: 'philadelphia-76ers', title: 'Philadelphia 76ers', imageUrl: '' },
      { id: 'milwaukee-bucks', title: 'Milwaukee Bucks', imageUrl: '' },
      { id: 'new-york-knicks', title: 'New York Knicks', imageUrl: '' },
      { id: 'denver-nuggets', title: 'Denver Nuggets', imageUrl: '' },
      { id: 'houston-rockets', title: 'Houston Rockets', imageUrl: '' },
      { id: 'utah-jazz', title: 'Utah Jazz', imageUrl: '' },
      { id: 'oklahoma-city-thunder', title: 'Oklahoma City Thunder', imageUrl: '' },
      { id: 'toronto-raptors', title: 'Toronto Raptors', imageUrl: '' },
    ],
  },

  {
    id: 'movies-top',
    name: 'Фильмы',
    description: '~50 фильмов из топа',
    coverUrl: '/public/covers/movies.jpg',
    items: [
      { id: 'the-godfather', title: 'Крёстный отец', imageUrl: '' },
      { id: 'the-godfather-2', title: 'Крёстный отец 2', imageUrl: '' },
      { id: 'the-shawshank-redemption', title: 'Побег из Шоушенка', imageUrl: '' },
      { id: 'schindlers-list', title: 'Список Шиндлера', imageUrl: '' },
      { id: 'pulp-fiction', title: 'Криминальное чтиво', imageUrl: '' },
      { id: 'the-dark-knight', title: 'Тёмный рыцарь', imageUrl: '' },
      { id: 'forrest-gump', title: 'Форрест Гамп', imageUrl: '' },
      { id: 'inception', title: 'Начало', imageUrl: '' },
      { id: 'fight-club', title: 'Бойцовский клуб', imageUrl: '' },
      { id: 'the-matrix', title: 'Матрица', imageUrl: '' },
      { id: 'the-lord-of-the-rings-fotr', title: 'Властелин колец: Братство Кольца', imageUrl: '' },
      { id: 'the-lord-of-the-rings-ttt', title: 'Властелин колец: Две крепости', imageUrl: '' },
      { id: 'the-lord-of-the-rings-rotk', title: 'Властелин колец: Возвращение короля', imageUrl: '' },
      { id: 'interstellar', title: 'Интерстеллар', imageUrl: '' },
      { id: 'se7en', title: 'Семь', imageUrl: '' },
      { id: 'the-green-mile', title: 'Зелёная миля', imageUrl: '' },
      { id: 'gladiator', title: 'Гладиатор', imageUrl: '' },
      { id: 'city-of-god', title: 'Город бога', imageUrl: '' },
      { id: 'goodfellas', title: 'Славные парни', imageUrl: '' },
      { id: 'the-prestige', title: 'Престиж', imageUrl: '' },
      { id: 'whiplash', title: 'Одержимость', imageUrl: '' },
      { id: 'parasite', title: 'Паразиты', imageUrl: '' },
      { id: 'the-silence-of-the-lambs', title: 'Молчание ягнят', imageUrl: '' },
      { id: 'the-usual-suspects', title: 'Подозрительные лица', imageUrl: '' },
      { id: 'saving-private-ryan', title: 'Спасти рядового Райана', imageUrl: '' },
      { id: 'back-to-the-future', title: 'Назад в будущее', imageUrl: '' },
      { id: 'the-departed', title: 'Отступники', imageUrl: '' },
      { id: 'once-upon-a-time-in-hollywood', title: 'Однажды в… Голливуде', imageUrl: '' },
      { id: 'the-wolf-of-wall-street', title: 'Волк с Уолл-стрит', imageUrl: '' },
      { id: 'oldboy', title: 'Олдбой', imageUrl: '' },
      { id: 'amelie', title: 'Амели', imageUrl: '' },
      
      { id: 'la-la-land', title: 'Ла-Ла Ленд', imageUrl: '' },
      { id: 'the-intouchables', title: '1+1', imageUrl: '' },
      { id: 'life-is-beautiful', title: 'Жизнь прекрасна', imageUrl: '' },
      { id: 'the-pianist', title: 'Пианист', imageUrl: '' },
      { id: 'the-truman-show', title: 'Шоу Трумана', imageUrl: '' },
      { id: 'casino', title: 'Казино', imageUrl: '' },
      { id: 'mad-max-fury-road', title: 'Безумный Макс: Дорога ярости', imageUrl: '' },
      { id: 'arrival', title: 'Прибытие', imageUrl: '' },
      { id: 'blade-runner-2049', title: 'Бегущий по лезвию 2049', imageUrl: '' },
      { id: 'joker', title: 'Джокер', imageUrl: '' },
      { id: 'dune-2021', title: 'Дюна (2021)', imageUrl: '' },
      { id: 'dune-part-two-2024', title: 'Дюна: Часть вторая', imageUrl: '' },
      
      { id: 'the-social-network', title: 'Социальная сеть', imageUrl: '' },
      { id: 'her-2013', title: 'Она', imageUrl: '' },
      { id: 'the-revenant', title: 'Выживший', imageUrl: '' },
      { id: '1917', title: '1917', imageUrl: '' },
      { id: 'the-grand-budapest-hotel', title: 'Отель «Гранд Будапешт»', imageUrl: '' },
      { id: 'get-out', title: 'Прочь', imageUrl: '' },
      { id: 'the-martian', title: 'Марсианин', imageUrl: '' },
      { id: 'oppenheimer-2023', title: 'Оппенгеймер', imageUrl: '' },
      { id: 'top-gun-maverick', title: 'Топ Ган: Мэверик', imageUrl: '' },
      { id: 'the-batman-2022', title: 'Бэтмен', imageUrl: '' },
      { id: 'knives-out', title: 'Достать ножи', imageUrl: '' },
      { id: 'ford-v-ferrari', title: 'Ford против Ferrari', imageUrl: '' },
      { id: 'the-irishman', title: 'Ирландец', imageUrl: '' },
      { id: 'the-big-short', title: 'Игра на понижение', imageUrl: '' },
      { id: 'spotlight-2015', title: 'В центре внимания', imageUrl: '' },
      { id: 'prisoners-2013', title: 'Пленницы', imageUrl: '' },
      { id: 'nightcrawler-2014', title: 'Стрингер', imageUrl: '' },
    ],
  },
]

export function getPublicTemplate(id: string) {
  return publicTemplates.find(t => t.id === id)
}


