import type { MediaItem } from './types'

export interface PublicTemplateDef {
  id: string
  name: string
  description: string
  coverUrl: string
  items: MediaItem[]
}

// All covers live in /public/covers/*. Posteres are auto-resolved from folders:
// posters, posters-actors, posters-basketball, posters-basketball-teams,
// posters-movies, posters-football, posters-football-players

export const publicTemplates: PublicTemplateDef[] = [
  {
    id: 'tv-2000-2025',
    name: 'Сериалы 2000–2025',
    description: 'Популярные сериалы с 2000 по 2025 годы',
    coverUrl: '/public/covers/series.png',
    items: [
      { id: 'breaking-bad', title: 'Во все тяжкие', imageUrl: '' },
      { id: 'game-of-thrones', title: 'Игра престолов', imageUrl: '' },
      { id: 'stranger-things', title: 'Очень странные дела', imageUrl: '' },
      { id: 'the-crown', title: 'Корона', imageUrl: '' },
      { id: 'chernobyl', title: 'Чернобыль', imageUrl: '' },
      { id: 'better-call-saul', title: 'Лучше звоните Солу', imageUrl: '' },
      { id: 'true-detective', title: 'Настоящий детектив', imageUrl: '' },
      { id: 'sherlock', title: 'Шерлок', imageUrl: '' },
      { id: 'house-md', title: 'Доктор Хаус', imageUrl: '' },
      { id: 'lost', title: 'Остаться в живых', imageUrl: '' },
      { id: 'dark', title: 'Тьма', imageUrl: '' },
      { id: 'black-mirror', title: 'Чёрное зеркало', imageUrl: '' },
      { id: 'the-boys', title: 'Пацаны', imageUrl: '' },
      { id: 'the-mandalorian', title: 'Мандалорец', imageUrl: '' },
      { id: 'the-last-of-us', title: 'Одни из нас', imageUrl: '' },
      { id: 'mr-robot', title: 'Мистер Робот', imageUrl: '' },
      { id: 'fargo', title: 'Фарго', imageUrl: '' },
      { id: 'westworld', title: 'Мир Дикого Запада', imageUrl: '' },
      { id: 'peaky-blinders', title: 'Острые козырьки', imageUrl: '' },
      { id: 'the-witcher', title: 'Ведьмак', imageUrl: '' },
      { id: 'the-office-us', title: 'Офис (США)', imageUrl: '' },
      { id: 'the-wire', title: 'Прослушка', imageUrl: '' },
      { id: 'band-of-brothers', title: 'Братья по оружию', imageUrl: '' },
      { id: 'the-pacific', title: 'Тихий океан', imageUrl: '' },
      { id: 'dexter', title: 'Декстер', imageUrl: '' },
      { id: 'homeland', title: 'Родина', imageUrl: '' },
      { id: 'narcos', title: 'Нарко', imageUrl: '' },
      { id: 'mindhunter', title: 'Охотник за разумом', imageUrl: '' },
      { id: 'succession', title: 'Наследники', imageUrl: '' },
      { id: 'ted-lasso', title: 'Тед Лассо', imageUrl: '' },
      { id: 'the-handmaids-tale', title: 'Рассказ служанки', imageUrl: '' },
      { id: 'the-queen-gambit', title: 'Ход королевы', imageUrl: '' },
      { id: 'shameless-us', title: 'Бесстыдники (США)', imageUrl: '' },
      { id: 'vikings', title: 'Викинги', imageUrl: '' },
      { id: 'the-expanse', title: 'Пространство', imageUrl: '' },
      { id: 'the-umbrella-academy', title: 'Академия «Амбрелла»', imageUrl: '' },
      { id: 'the-haunting-of-hill-house', title: 'Призраки дома на холме', imageUrl: '' },
      { id: 'severance', title: 'Разделение', imageUrl: '' },
      { id: 'the-bear', title: 'Медведь', imageUrl: '' },
      { id: 'the-white-lotus', title: 'Белый лотос', imageUrl: '' },
      { id: 'the-morning-show', title: 'Утреннее шоу', imageUrl: '' },
      { id: 'silo', title: 'Сило', imageUrl: '' },
      { id: 'andor', title: 'Андор', imageUrl: '' },
      { id: 'the-night-manager', title: 'Ночной администратор', imageUrl: '' },
      { id: 'the-leftovers', title: 'Оставленные', imageUrl: '' },
    ],
  },

  {
    id: 'football-teams',
    name: 'Футбольные команды',
    description: 'Популярные клубы',
    coverUrl: '/public/covers/footbal.jpg',
    items: [
      { id: 'real-madrid', title: 'Real Madrid', imageUrl: '' },
      { id: 'barcelona', title: 'Barcelona', imageUrl: '' },
      { id: 'manchester-united', title: 'Manchester United', imageUrl: '' },
      { id: 'manchester-city', title: 'Manchester City', imageUrl: '' },
      { id: 'bayern-munich', title: 'Bayern Munich', imageUrl: '' },
      { id: 'psg', title: 'PSG', imageUrl: '' },
      { id: 'liverpool', title: 'Liverpool', imageUrl: '' },
      { id: 'chelsea', title: 'Chelsea', imageUrl: '' },
      { id: 'arsenal', title: 'Arsenal', imageUrl: '' },
      { id: 'tottenham-hotspur', title: 'Tottenham Hotspur', imageUrl: '' },
      { id: 'atletico-madrid', title: 'Atletico Madrid', imageUrl: '' },
      { id: 'juventus', title: 'Juventus', imageUrl: '' },
      { id: 'ac-milan', title: 'AC Milan', imageUrl: '' },
      { id: 'inter-milan', title: 'Inter Milan', imageUrl: '' },
      { id: 'borussia-dortmund', title: 'Borussia Dortmund', imageUrl: '' },
      { id: 'rb-leipzig', title: 'RB Leipzig', imageUrl: '' },
      { id: 'bayer-leverkusen', title: 'Bayer Leverkusen', imageUrl: '' },
      { id: 'sevilla', title: 'Sevilla', imageUrl: '' },
      { id: 'valencia', title: 'Valencia', imageUrl: '' },
      { id: 'napoli', title: 'Napoli', imageUrl: '' },
      { id: 'roma', title: 'AS Roma', imageUrl: '' },
      { id: 'lazio', title: 'Lazio', imageUrl: '' },
      { id: 'ajax', title: 'Ajax', imageUrl: '' },
      { id: 'benfica', title: 'Benfica', imageUrl: '' },
      { id: 'porto', title: 'Porto', imageUrl: '' },
    ],
  },

  {
    id: 'hollywood-actors',
    name: 'Голливудские актёры',
    description: 'Классические и современные звёзды',
    coverUrl: '/public/covers/film-stars.png',
    items: [
      { id: 'leonardo-dicaprio', title: 'Leonardo DiCaprio', imageUrl: '' },
      { id: 'brad-pitt', title: 'Brad Pitt', imageUrl: '' },
      { id: 'meryl-streep', title: 'Meryl Streep', imageUrl: '' },
      { id: 'denzel-washington', title: 'Denzel Washington', imageUrl: '' },
      { id: 'emma-stone', title: 'Emma Stone', imageUrl: '' },
      { id: 'ryan-gosling', title: 'Ryan Gosling', imageUrl: '' },
      { id: 'tom-cruise', title: 'Tom Cruise', imageUrl: '' },
      { id: 'robert-downey-jr', title: 'Robert Downey Jr.', imageUrl: '' },
      { id: 'scarlett-johansson', title: 'Scarlett Johansson', imageUrl: '' },
      { id: 'chris-evans', title: 'Chris Evans', imageUrl: '' },
      { id: 'natalie-portman', title: 'Natalie Portman', imageUrl: '' },
      { id: 'anne-hathaway', title: 'Anne Hathaway', imageUrl: '' },
      { id: 'matt-damon', title: 'Matt Damon', imageUrl: '' },
      { id: 'ben-affleck', title: 'Ben Affleck', imageUrl: '' },
      { id: 'christian-bale', title: 'Christian Bale', imageUrl: '' },
      { id: 'joaquin-phoenix', title: 'Joaquin Phoenix', imageUrl: '' },
      { id: 'ryan-reynolds', title: 'Ryan Reynolds', imageUrl: '' },
      { id: 'jennifer-lawrence', title: 'Jennifer Lawrence', imageUrl: '' },
      { id: 'margot-robbie', title: 'Margot Robbie', imageUrl: '' },
      { id: 'zendaya', title: 'Zendaya', imageUrl: '' },
      { id: 'robert-de-niro', title: 'Robert De Niro', imageUrl: '' },
      { id: 'al-pacino', title: 'Al Pacino', imageUrl: '' },
      { id: 'tom-hanks', title: 'Tom Hanks', imageUrl: '' },
      { id: 'morgan-freeman', title: 'Morgan Freeman', imageUrl: '' },
      { id: 'samuel-l-jackson', title: 'Samuel L. Jackson', imageUrl: '' },
      { id: 'keanu-reeves', title: 'Keanu Reeves', imageUrl: '' },
      { id: 'hugh-jackman', title: 'Hugh Jackman', imageUrl: '' },
      { id: 'will-smith', title: 'Will Smith', imageUrl: '' },
      { id: 'johnny-depp', title: 'Johnny Depp', imageUrl: '' },
      { id: 'cate-blanchett', title: 'Cate Blanchett', imageUrl: '' },
      { id: 'keira-knightley', title: 'Keira Knightley', imageUrl: '' },
      { id: 'charlize-theron', title: 'Charlize Theron', imageUrl: '' },
      { id: 'emily-blunt', title: 'Emily Blunt', imageUrl: '' },
      { id: 'florence-pugh', title: 'Florence Pugh', imageUrl: '' },
      { id: 'tom-hardy', title: 'Tom Hardy', imageUrl: '' },
      { id: 'benedict-cumberbatch', title: 'Benedict Cumberbatch', imageUrl: '' },
      { id: 'matthew-mcconaughey', title: 'Matthew McConaughey', imageUrl: '' },
      { id: 'daniel-craig', title: 'Daniel Craig', imageUrl: '' },
      { id: 'idris-elba', title: 'Idris Elba', imageUrl: '' },
      { id: 'henry-cavill', title: 'Henry Cavill', imageUrl: '' },
      { id: 'zendaya', title: 'Zendaya', imageUrl: '' },
      { id: 'jake-gyllenhaal', title: 'Jake Gyllenhaal', imageUrl: '' },
      { id: 'andrew-garfield', title: 'Andrew Garfield', imageUrl: '' },
      { id: 'adam-driver', title: 'Adam Driver', imageUrl: '' },
      { id: 'oscar-isaac', title: 'Oscar Isaac', imageUrl: '' },
      { id: 'pedro-pascal', title: 'Pedro Pascal', imageUrl: '' },
      { id: 'tom-holland', title: 'Tom Holland', imageUrl: '' },
      { id: 'woody-harrelson', title: 'Woody Harrelson', imageUrl: '' },
      { id: 'colin-farrell', title: 'Colin Farrell', imageUrl: '' },
      { id: 'jesse-eisenberg', title: 'Jesse Eisenberg', imageUrl: '' },
      { id: 'aaron-paul', title: 'Aaron Paul', imageUrl: '' },
    ],
  },

  {
    id: 'basketball-teams',
    name: 'Баскетбольные команды',
    description: 'Популярные клубы NBA',
    coverUrl: '/public/covers/basketball-teams.jpg',
    items: [
      { id: 'los-angeles-lakers', title: 'Los Angeles Lakers', imageUrl: '' },
      { id: 'boston-celtics', title: 'Boston Celtics', imageUrl: '' },
      { id: 'chicago-bulls', title: 'Chicago Bulls', imageUrl: '' },
      { id: 'golden-state-warriors', title: 'Golden State Warriors', imageUrl: '' },
      { id: 'miami-heat', title: 'Miami Heat', imageUrl: '' },
      { id: 'san-antonio-spurs', title: 'San Antonio Spurs', imageUrl: '' },
      { id: 'dallas-mavericks', title: 'Dallas Mavericks', imageUrl: '' },
      { id: 'phoenix-suns', title: 'Phoenix Suns', imageUrl: '' },
      { id: 'philadelphia-76ers', title: 'Philadelphia 76ers', imageUrl: '' },
      { id: 'milwaukee-bucks', title: 'Milwaukee Bucks', imageUrl: '' },
      { id: 'new-york-knicks', title: 'New York Knicks', imageUrl: '' },
      { id: 'denver-nuggets', title: 'Denver Nuggets', imageUrl: '' },
      { id: 'houston-rockets', title: 'Houston Rockets', imageUrl: '' },
      { id: 'utah-jazz', title: 'Utah Jazz', imageUrl: '' },
      { id: 'oklahoma-city-thunder', title: 'Oklahoma City Thunder', imageUrl: '' },
      { id: 'toronto-raptors', title: 'Toronto Raptors', imageUrl: '' },
    ],
  },

  {
    id: 'movies-top',
    name: 'Фильмы',
    description: '40 фильмов из топа',
    coverUrl: '/public/covers/movies.jpg',
    items: [
      { id: 'the-godfather', title: 'Крёстный отец', imageUrl: '' },
      { id: 'the-godfather-2', title: 'Крёстный отец 2', imageUrl: '' },
      { id: 'the-shawshank-redemption', title: 'Побег из Шоушенка', imageUrl: '' },
      { id: 'schindlers-list', title: 'Список Шиндлера', imageUrl: '' },
      { id: 'pulp-fiction', title: 'Криминальное чтиво', imageUrl: '' },
      { id: 'the-dark-knight', title: 'Тёмный рыцарь', imageUrl: '' },
      { id: 'forrest-gump', title: 'Форрест Гамп', imageUrl: '' },
      { id: 'inception', title: 'Начало', imageUrl: '' },
      { id: 'fight-club', title: 'Бойцовский клуб', imageUrl: '' },
      { id: 'the-matrix', title: 'Матрица', imageUrl: '' },
      { id: 'the-lord-of-the-rings-fotr', title: 'Властелин колец: Братство Кольца', imageUrl: '' },
      { id: 'the-lord-of-the-rings-ttt', title: 'Властелин колец: Две крепости', imageUrl: '' },
      { id: 'the-lord-of-the-rings-rotk', title: 'Властелин колец: Возвращение короля', imageUrl: '' },
      { id: 'interstellar', title: 'Интерстеллар', imageUrl: '' },
      { id: 'se7en', title: 'Семь', imageUrl: '' },
      { id: 'the-green-mile', title: 'Зелёная миля', imageUrl: '' },
      { id: 'gladiator', title: 'Гладиатор', imageUrl: '' },
      { id: 'city-of-god', title: 'Город бога', imageUrl: '' },
      { id: 'goodfellas', title: 'Славные парни', imageUrl: '' },
      { id: 'the-prestige', title: 'Престиж', imageUrl: '' },
      { id: 'whiplash', title: 'Одержимость', imageUrl: '' },
      { id: 'parasite', title: 'Паразиты', imageUrl: '' },
      { id: 'the-silence-of-the-lambs', title: 'Молчание ягнят', imageUrl: '' },
      { id: 'the-usual-suspects', title: 'Подозрительные лица', imageUrl: '' },
      { id: 'saving-private-ryan', title: 'Спасти рядового Райана', imageUrl: '' },
      { id: 'back-to-the-future', title: 'Назад в будущее', imageUrl: '' },
      { id: 'the-departed', title: 'Отступники', imageUrl: '' },
      { id: 'once-upon-a-time-in-hollywood', title: 'Однажды в… Голливуде', imageUrl: '' },
      { id: 'the-wolf-of-wall-street', title: 'Волк с Уолл-стрит', imageUrl: '' },
      { id: 'oldboy', title: 'Олдбой', imageUrl: '' },
      { id: 'amelie', title: 'Амели', imageUrl: '' },
      { id: 'grave-of-the-fireflies', title: 'Могила светлячков', imageUrl: '' },
      { id: 'spirited-away', title: 'Унесённые призраками', imageUrl: '' },
      { id: 'your-name', title: 'Твоё имя', imageUrl: '' },
      { id: 'la-la-land', title: 'Ла-Ла Ленд', imageUrl: '' },
      { id: 'the-intouchables', title: '1+1', imageUrl: '' },
      { id: 'life-is-beautiful', title: 'Жизнь прекрасна', imageUrl: '' },
      { id: 'the-pianist', title: 'Пианист', imageUrl: '' },
      { id: 'the-truman-show', title: 'Шоу Трумана', imageUrl: '' },
      { id: 'casino', title: 'Казино', imageUrl: '' },
    ],
  },
]

export function getPublicTemplate(id: string) {
  return publicTemplates.find(t => t.id === id)
}


